import type { Product, Order, User, StockTransaction } from "./types"

export const dummyUsers: User[] = [
  {
    id: "1",
    name: "Admin User",
    email: "admin@example.com",
    role: "admin",
  },
  {
    id: "2",
    name: "John Distributor",
    email: "john@bar.com",
    role: "distributor",
    businessType: "bar-restaurant",
  },
  {
    id: "3",
    name: "Sarah Market",
    email: "sarah@market.com",
    role: "distributor",
    businessType: "supermarket",
  },
  {
    id: "4",
    name: "Mike's Bistro",
    email: "mike@bistro.com",
    role: "distributor",
    businessType: "bar-restaurant",
  },
  {
    id: "5",
    name: "Emma's Grocery",
    email: "emma@grocery.com",
    role: "distributor",
    businessType: "supermarket",
  },
  {
    id: "6",
    name: "David's Pub",
    email: "david@pub.com",
    role: "distributor",
    businessType: "bar-restaurant",
  },
  {
    id: "7",
    name: "Lisa's Superstore",
    email: "lisa@superstore.com",
    role: "distributor",
    businessType: "supermarket",
  },
]

export const dummyProducts: Product[] = [
  // Bar/Restaurant Products
  {
    id: "p1",
    name: "Premium Wine Selection",
    description: "Curated collection of fine wines",
    price: 45.99,
    category: "Beverages",
    businessType: "bar-restaurant",
    stock: 120,
    image: "/wine-bottles.jpg",
  },
  {
    id: "p2",
    name: "Craft Beer Pack",
    description: "Assorted craft beers from local breweries",
    price: 32.5,
    category: "Beverages",
    businessType: "bar-restaurant",
    stock: 85,
    image: "/craft-beer-selection.png",
  },
  {
    id: "p3",
    name: "Premium Spirits",
    description: "Top-shelf liquor selection",
    price: 89.99,
    category: "Beverages",
    businessType: "bar-restaurant",
    stock: 45,
    image: "/spirits-bottles.jpg",
  },
  {
    id: "p4",
    name: "Fresh Seafood",
    description: "Daily catch of premium seafood",
    price: 65.0,
    category: "Food",
    businessType: "bar-restaurant",
    stock: 30,
    image: "/fresh-seafood-display.png",
  },
  {
    id: "p5",
    name: "Wagyu Beef",
    description: "Premium grade Wagyu beef cuts",
    price: 125.0,
    category: "Food",
    businessType: "bar-restaurant",
    stock: 20,
    image: "/wagyu-beef-steak.png",
  },
  {
    id: "p6",
    name: "Artisan Cheese Board",
    description: "Selection of imported cheeses",
    price: 38.5,
    category: "Food",
    businessType: "bar-restaurant",
    stock: 55,
    image: "/cheese-board.png",
  },

  // Supermarket Products
  {
    id: "p7",
    name: "Organic Vegetables Box",
    description: "Fresh organic seasonal vegetables",
    price: 24.99,
    category: "Produce",
    businessType: "supermarket",
    stock: 150,
    image: "/organic-vegetables-display.png",
  },
  {
    id: "p8",
    name: "Fresh Fruit Basket",
    description: "Assorted fresh fruits",
    price: 19.99,
    category: "Produce",
    businessType: "supermarket",
    stock: 200,
    image: "/vibrant-fruit-basket.png",
  },
  {
    id: "p9",
    name: "Dairy Products Pack",
    description: "Milk, cheese, yogurt, and butter",
    price: 28.5,
    category: "Dairy",
    businessType: "supermarket",
    stock: 180,
    image: "/assorted-dairy.png",
  },
  {
    id: "p10",
    name: "Bakery Fresh Bread",
    description: "Daily baked artisan breads",
    price: 8.99,
    category: "Bakery",
    businessType: "supermarket",
    stock: 250,
    image: "/artisan-bread.png",
  },
  {
    id: "p11",
    name: "Meat Selection",
    description: "Premium cuts of beef, pork, and chicken",
    price: 45.0,
    category: "Meat",
    businessType: "supermarket",
    stock: 95,
    image: "/fresh-meat.png",
  },
  {
    id: "p12",
    name: "Pantry Essentials",
    description: "Rice, pasta, canned goods, and spices",
    price: 35.99,
    category: "Pantry",
    businessType: "supermarket",
    stock: 300,
    image: "/pantry-items.png",
  },
]

export const dummyOrders: Order[] = [
  {
    id: "o1",
    distributorId: "2",
    distributorName: "John Distributor",
    businessType: "bar-restaurant",
    items: [
      { product: dummyProducts[0], quantity: 5 },
      { product: dummyProducts[1], quantity: 10 },
    ],
    total: 554.95,
    status: "pending",
    createdAt: new Date("2025-01-10T10:30:00"),
    updatedAt: new Date("2025-01-10T10:30:00"),
  },
  {
    id: "o2",
    distributorId: "3",
    distributorName: "Sarah Market",
    businessType: "supermarket",
    items: [
      { product: dummyProducts[6], quantity: 20 },
      { product: dummyProducts[7], quantity: 15 },
    ],
    total: 799.65,
    status: "processing",
    createdAt: new Date("2025-01-09T14:20:00"),
    updatedAt: new Date("2025-01-10T09:15:00"),
  },
  {
    id: "o3",
    distributorId: "2",
    distributorName: "John Distributor",
    businessType: "bar-restaurant",
    items: [{ product: dummyProducts[4], quantity: 3 }],
    total: 375.0,
    status: "completed",
    createdAt: new Date("2025-01-08T16:45:00"),
    updatedAt: new Date("2025-01-09T11:30:00"),
  },
  {
    id: "o4",
    distributorId: "3",
    distributorName: "Sarah Market",
    businessType: "supermarket",
    items: [
      { product: dummyProducts[8], quantity: 25 },
      { product: dummyProducts[9], quantity: 30 },
      { product: dummyProducts[11], quantity: 15 },
    ],
    total: 1451.35,
    status: "completed",
    createdAt: new Date("2025-01-07T08:00:00"),
    updatedAt: new Date("2025-01-08T10:00:00"),
  },
]

export const dummyStockTransactions: StockTransaction[] = [
  {
    id: "st1",
    productId: "p1",
    productName: "Premium Wine Selection",
    type: "in",
    quantity: 50,
    reason: "New stock delivery",
    performedBy: "Admin User",
    createdAt: new Date("2025-01-05T09:00:00"),
  },
  {
    id: "st2",
    productId: "p7",
    productName: "Organic Vegetables Box",
    type: "in",
    quantity: 100,
    reason: "Weekly restock",
    performedBy: "Admin User",
    createdAt: new Date("2025-01-06T10:30:00"),
  },
  {
    id: "st3",
    productId: "p4",
    productName: "Fresh Seafood",
    type: "out",
    quantity: 15,
    reason: "Damaged goods",
    performedBy: "Admin User",
    createdAt: new Date("2025-01-07T14:20:00"),
  },
]
